title: Graphically Speaking
tagline: 
description: A WIP show by Central Saint Martinsâ€™ MA Graphic Communication Design.

marquee_top:
  - "We are now off air"
  - "Thanks for joining us!"
  - "All broadcasts archived online ðŸ‘‡"
marquee_bottom:
  - "Graphically Speaking"
  - "Opening times: "
  - "Thurs 11th January 2018 6pmâ€“10pm"
  - "Fri 12th January 2018 12pmâ€“7pm"
  - "Sat 13th January 2018 10amâ€“4pm"
  - "Central Saint Martins, 1, Granary Building, Granary Square, Kings Cross, London, N1C 4AA"

collections: 
  people:
    output: true
    permalink: /people/:path/
    sort_by: time

defaults:
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "people"

kramdown:
  auto_ids: false

keep_files:
  - "/dist/"
exclude:
  - "README.md"
  - "package.json"
  - "package-lock.json"
  - "/src/"

safe: true
